name: Publish to NuGet
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotNET
        id: install_dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      - name: Publish NuGet Package
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/TTools.Bot.Lib.Parser/TTools.Bot.Lib.Parser.csproj
          PACKAGE_NAME: TTools.Bot.Lib.Parser
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: false
